---
- name: "DEBUG : Interfaces L1 raw variables"
  ansible.builtin.debug:
    var: cisco_interfaces_l1
  tags: [never, debug]

- name: "CHECKS: Assert L1 variable types"
  ansible.builtin.assert:
    that:
      - cisco_interfaces_l1 is sequence and cisco_interfaces_l1 is not string
    fail_msg: "One or more variables have incorrect data types!"
    quiet: true
  tags: [l1, checks]

- name: Gather and purge unused interfaces
  when: cisco_interfaces_state == "overridden"
  tags: [l1]
  block:
    - name: Gather all existing interfaces
      cisco.ios.ios_interfaces:
        state: gathered
      register: _cisco_interfaces_l1_gathered
      tags: [debug]

    - name: Select L1 interfaces to remove
      vars:
        _cisco_interfaces_l1_reserved_names: "{{ cisco_interfaces_l1_reserved | default([]) | map(attribute='name') | list }}"
        _cisco_interfaces_l1_names: "{{ cisco_interfaces_l1 | default([]) | map(attribute='name') | list }}"
      ansible.builtin.set_fact:
        _cisco_interfaces_l1_to_purge: >-
          {%- set interface_names = _cisco_interfaces_l1_gathered.gathered | default([])
          | map(attribute="name")
          | select("match", "(?i)vlan|loopback")
          | difference(_cisco_interfaces_l1_reserved_names)
          | difference(_cisco_interfaces_l1_names) -%}
          {%- set result = [] -%}
          {%- for interface_name in interface_names -%}
            {%- set _ = result.append({"name": interface_name}) -%}
          {%- endfor -%}
          {{ result }}
      tags: [debug]

    - name: "DEBUG : Interfaces L1 to delete"
      ansible.builtin.debug:
        msg:
          - "interfaces_to_purge: {{ _cisco_interfaces_l1_to_purge }}"
      tags: [never, debug]

    - name: Purge unused interfaces
      cisco.ios.ios_interfaces:
        config: "{{ _cisco_interfaces_l1_to_purge }}"
        state: purged
      when: _cisco_interfaces_l1_to_purge | length > 0

- name: Prepare a final list of L1 interfaces
  ansible.builtin.set_fact:
    _cisco_interfaces_l1_final: >-
      {{
        (cisco_interfaces_l1 + cisco_interfaces_l1_reserved) | unique(attribute='name') | list
        if cisco_interfaces_state == 'overridden'
        else cisco_interfaces_l1
      }}
  tags: [l1, debug]

- name: "DEBUG : Interfaces L1 final variables"
  ansible.builtin.debug:
    var: _cisco_interfaces_l1_final
  tags: [never, debug]

- name: Configure L1 interface settings
  cisco.ios.ios_interfaces:
    config: "{{ _cisco_interfaces_l1_final }}"
    state: "{{ cisco_interfaces_state }}"
  tags: [l1]
