---
- name: "DEBUG : Interfaces L2 raw variables"
  ansible.builtin.debug:
    var: cisco_interfaces_l2
  tags: [never, debug]

- name: "CHECKS: Assert L2 variable types"
  ansible.builtin.assert:
    that:
      - cisco_interfaces_l2 is sequence and cisco_interfaces_l2 is not string
    fail_msg: "One or more variables have incorrect data types!"
    quiet: true
  tags: [l2, checks]

- name: Configure L2 interface settings
  cisco.ios.ios_l2_interfaces:
    config: "{{ cisco_interfaces_l2 }}"
    state: "{{ cisco_interfaces_state }}"
  tags: [l2]
