---
- name: System task list include
  ansible.builtin.include_tasks: system.yaml
  tags: [system, system:checks, system:debug, checks, debug]

- name: MTU task list include
  ansible.builtin.include_tasks: mtu.yaml
  tags: [mtu, mtu:checks, mtu:debug, checks, debug]

- name: Users task list include
  ansible.builtin.include_tasks: users.yaml
  tags: [users, users:checks, users:debug, checks, debug]

- name: SSH task list include
  ansible.builtin.include_tasks: ssh.yaml
  tags: [ssh, ssh:checks, ssh:debug, checks, debug]

- name: Banners task list include
  ansible.builtin.include_tasks: banners.yaml
  tags: [banners, banners:checks, banners:debug, checks, debug]

- name: Hardening task list include
  ansible.builtin.include_tasks: hardening.yaml
  tags: [hardening, hardening:checks, hardening:debug, checks, debug]
