---
- name: "DEBUG : MTU variables"
  ansible.builtin.debug:
    msg:
      - "jumbo_mtu_size: {{ cisco_base_jumbo_mtu_size }}"
      - "reload_device: {{ cisco_base_reload_device | default(false) }}"
  tags: [never, debug]

- name: "CHECKS: Assert MTU variable types"
  ansible.builtin.assert:
    that:
      - cisco_base_jumbo_mtu_size is number
      - cisco_base_reload_device is boolean
    fail_msg: "One or more MTU variables have incorrect data types!"
    quiet: true
  tags: [cisco_base, mtu, checks]

- name: "CHECKS: Assert MTU values"
  ansible.builtin.assert:
    that:
      - cisco_base_jumbo_mtu_size >= 1500
      - cisco_base_jumbo_mtu_size <= 9198
    fail_msg: "cisco_base_jumbo_mtu_size must be between 1500 and 9198!"
    quiet: true
  tags: [cisco_base, mtu, checks]

- name: Check current Jumbo MTU value
  cisco.ios.ios_command:
    commands:
      - "show system mtu"
  register: _jumbo_mtu_value
  changed_when: false
  tags: [cisco_base, mtu]

- name: Configure Jumbo MTU settings
  cisco.ios.ios_config:
    lines:
      - "system mtu jumbo {{ cisco_base_jumbo_mtu_size }}"
  when: "('System Jumbo MTU size is ' ~ cisco_base_jumbo_mtu_size | string ~ ' bytes') not in _jumbo_mtu_value.stdout[0]"
  notify: Reload device
  tags: [cisco_base, mtu]
